### ISSUE TITLE
How to implement AMDKD+EAS?

### ISSUE THREAD

**Issue by ytytbyt** [jieyibi/AMDKD#1]
Thank you for your insightful work and for releasing the code. I am wondering how to implement AMDKD+EAS with your code? Could you please share the source code for AMDKD+EAS?

**Comment by jieyibi** [comment]
Hi, thanks for your interest in our work. We have uploaded the code for AMDKD+EAS.

**Comment by ytytbyt** [comment]
Many thanks!
