### ISSUE TITLE
About model train question

### ISSUE THREAD

**Issue by oooo111** [jieyibi/AMDKD#2]
About May I ask how to solve a large number of Inf problems in both student_logp and teacher_logp during model training?

**Comment by jieyibi** [comment]
Hi, you can add a very small value (e.g. 0.00001) to the probabilities before calculating _logP_ (i.e. _student_logp_ and _teacher_logp_) to avoid the occurrence of log0 and to accordingly solve the Inf issue. We have updated our code. Please check it.
