### ISSUE TITLE
Table 11: Full generalization results on CVRPLIB

### ISSUE THREAD

**Issue by MLgeek7325** [jieyibi/AMDKD#3]
Thanks for your insightful work. I would like to ask if 【Table 11: Full generalization results on CVRPLIB】 was obtained using a student model trained on the cvrp-100 and decoded by [sampling-1280]?

**Comment by jieyibi** [comment]
Thanks for your interest in our work. 

Yes, the results in Table 11 were obtained from the models trained on CVRP-100. For the AM-based methods, we sampled 1,280 solutions for inference; and for the POMO-based methods, we adopted the greedy rollout with ×8 augments following the original settings of POMO.

**Comment by MLgeek7325** [comment]
@jieyibi Thank you for your quick response~
