### ISSUE TITLE
Contributing to RL4CO 🚀

### ISSUE THREAD

**Issue by fedebotu** [jieyibi/AMDKD#4]
Hi there 👋🏼

Great job with your paper and code implementation of AMDKD~

Dropping by since we are actively developing [RL4CO](https://github.com/kaist-silab/rl4co), a library for all things Reinforcement Learning for Combinatorial Optimization. The idea is to make everything as easy to use and modular as possible in the hope of helping practitioners and researchers with the help of some recent software (such as TorchRL, TensorDict, PyTorch Lightning, FlashAttention, and Hydra). 

We did not have enough time to include your work in the library so far, but believe that AMDKD would be fairly easy to integrate and it would also contribute in terms of generalization studies. If you are interested in contributing/collaborating, feel free to leave PRs/issues or [contact us ](https://join.slack.com/t/rl4co/shared_invite/zt-1ytz2c1v4-0IkQ8NQH4TRXIX8PrRmDhQ) anytime 😉

**Comment by jieyibi** [comment]
Hi Federico~

It is a great pleasure to contribute to RL4CO. But recently, I am quite busy with my study. If it is still needed to include AMDKD in your library, I will be happy to help when I am available. Sorry for the late reply.  

Thank you for your interest in AMDKD.

**Comment by fedebotu** [comment]
Don't worry. You are welcome whenever you have time, feel free to contact us anytime :)
